---
abstract: 'Plack session store backed by a Catmandu::Store'
author:
  - 'Nicolas Steenlant <nicolas.steenlant@ugent.be>'
build_requires:
  Software::License: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Session-Store-Catmandu
provides:
  Plack::Session::Store::Catmandu:
    file: lib/Plack/Session/Store/Catmandu.pm
    version: 0.02
requires:
  Catmandu: 0.03
  Plack::Session::Store: 0.15
  perl: v5.10.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
